[project]
name = "agent-service-analyst"
version = "0.1.0"
description = "Fraud detection System"
requires-python = "==3.11.13"
dependencies = [
    "langchain>=1.0.0a7",
    "langchain-openai>=0.3.33",
    "langgraph>=1.0.0a3",
    "python-dotenv>=1.1.1",
    "starlette>=0.48.0",
]
