server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        regex: (.+)
        target_label: compose_service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        regex: (.+)
        target_label: compose_project
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_io_kubernetes_pod_name]
        regex: (.+)
        target_label: pod
    # No pipeline stages by default - promtail will forward raw log lines.
    # If your application emits structured JSON logs, add pipeline stages to extract fields.
